
-- This script inserts a list of sample IELTS questions into your database.
-- It uses "ON CONFLICT" to avoid creating duplicate questions if they already exist.
INSERT INTO public.sample_questions (category, question, time_limit, word_count, title)
VALUES
('Technology', 'Technology is making communication easier in today''s world, but at the expense of personal contact. Do you agree or disagree?', '40 minutes', '250+ words', 'Technology is making communication easier in today''s world, but at the expense of personal contact'),
('Education', 'Some people think that universities should provide graduates with the knowledge and skills needed in the workplace. Others think that the true function of a university should be to give access to knowledge for its own sake. What is your opinion?', '40 minutes', '250+ words', 'Some people think that universities should provide graduates with the knowledge and skills needed in the workplace'),
('Environment', 'Some people believe that the best way to protect the environment is for the government to impose strict regulations on businesses and individuals. Others argue that individuals should take more responsibility. Discuss both views and give your own opinion.', '40 minutes', '250+ words', 'Some people believe that the best way to protect the environment is for the government to impose strict regulations on businesses and individuals'),
('Health', 'Preventive medicine is becoming more and more important in modern society. Some people think that governments should invest more in preventive measures rather than in treatments. To what extent do you agree or disagree?', '40 minutes', '250+ words', 'Preventive medicine is becoming more and more important in modern society'),
('Social Issues', 'In many countries, the gap between the rich and the poor is widening. What problems can this cause, and what are the solutions?', '40 minutes', '250+ words', 'In many countries, the gap between the rich and the poor is widening'),
('Media', 'The media plays a significant role in shaping public opinion. To what extent do you think the media influences society?', '40 minutes', '250+ words', 'The media plays a significant role in shaping public opinion'),
('Young People', 'Many young people today are leaving their rural hometowns to work in big cities. What are the reasons for this trend? What are the advantages and disadvantages of this development?', '40 minutes', '250+ words', 'Many young people today are leaving their rural hometowns to work in big cities'),
('Family', 'The traditional family structure has changed in recent years. What are the causes of these changes, and what impact have they had on society?', '40 minutes', '250+ words', 'The traditional family structure has changed in recent years'),
('Culture', 'Some people believe that it is important for a country to preserve its traditional culture. Others argue that culture should be allowed to evolve and change with time. Discuss both views and give your opinion.', '40 minutes', '250+ words', 'Some people believe that it is important for a country to preserve its traditional culture'),
('Lifestyle', 'The fast pace of modern life is having a negative effect on people''s health and well-being. What are the main problems associated with a fast-paced lifestyle, and what can be done to reduce them?', '40 minutes', '250+ words', 'The fast pace of modern life is having a negative effect on people''s health and well-being'),
('Education', 'Some people believe that students should be taught in mixed-ability classes, while others think that students should be streamed according to their academic ability. Discuss both views and give your opinion.', '40 minutes', '250+ words', 'Some people believe that students should be taught in mixed-ability classes, while others think that students should be streamed according to their academic ability'),
('Environment', 'Many people believe that individuals can do little to help the environment, and that it is the responsibility of governments and large corporations. To what extent do you agree or disagree?', '40 minutes', '250+ words', 'Many people believe that individuals can do little to help the environment, and that it is the responsibility of governments and large corporations'),
('Technology', 'The use of artificial intelligence is growing rapidly. What are the potential benefits and drawbacks of this development?', '40 minutes', '250+ words', 'The use of artificial intelligence is growing rapidly'),
('Health', 'Many people are choosing to eat vegetarian diets. Why are people choosing this type of diet? Do the advantages of vegetarianism outweigh the disadvantages?', '40 minutes', '250+ words', 'Many people are choosing to eat vegetarian diets'),
('Social Issues', 'Consumerism is becoming increasingly prevalent in many countries. What are the positive and negative effects of a consumerist society?', '40 minutes', '250+ words', 'Consumerism is becoming increasingly prevalent in many countries'),
('Advertisement', 'Advertising aimed at children should be banned. To what extent do you agree or disagree?', '40 minutes', '250+ words', 'Advertising aimed at children should be banned'),
('Children', 'Children today are under more pressure than ever before. What are the causes of this pressure, and what can be done to alleviate it?', '40 minutes', '250+ words', 'Children today are under more pressure than ever before'),
('Old People', 'In many societies, the elderly are not respected as they were in the past. What are the reasons for this? What problems might this cause?', '40 minutes', '250+ words', 'In many societies, the elderly are not respected as they were in the past'),
('Foreign Language', 'Learning a foreign language is essential for success in today''s globalized world. To what extent do you agree or disagree?', '40 minutes', '250+ words', 'Learning a foreign language is essential for success in today''s globalized world'),
('Ethical Issues', 'Animal testing is a necessary evil in the development of new products and medicines. To what extent do you agree or disagree?', '40 minutes', '250+ words', 'Animal testing is a necessary evil in the development of new products and medicines'),
('Building', 'Modern architecture is often criticized for being bland and characterless. What are your views on this?', '40 minutes', '250+ words', 'Modern architecture is often criticized for being bland and characterless'),
('Drugs', 'The use of performance-enhancing drugs in sports is a major problem. What can be done to combat this issue?', '40 minutes', '250+ words', 'The use of performance-enhancing drugs in sports is a major problem')
ON CONFLICT (question) DO NOTHING;
