// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dowhqmirjcwppnqezztf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRvd2hxbWlyamN3cHBucWV6enRmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5OTI5NzAsImV4cCI6MjA2NTU2ODk3MH0.XFi9iefCKUVN248Iqa6J5VSLThCWRhWX-cNSLR6ytas";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);